apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: des-web-app
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "yc-clusterissuer"
spec:
  tls:
    - hosts:
        - des-web.despay.io
      secretName: des-web-secret
  rules:
    - host: des-web.despay.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: des-web-app
                port:
                  number: 8080